#!/bin/bash

# cgdb (and gdbtui) have bug where setting following options in inputrc breaks keystroke capture as well as 'quit'

file="$HOME/.inputrc"
config1="set editing-mode vi"
config2="set show-mode-in-prompt on"

disable_config() {
    sed --follow-symlinks -i -e "s/^\($config1\)/#\1/" -e "s/^\($config2\)/#\1/" "$file"
}

restore_config() {
    sed --follow-symlinks -i -e "s/^#\($config1\)/\1/" -e "s/^#\($config2\)/\1/" "$file"
}

disable_config && (sleep 2 && restore_config &) && cgdb "$@"
