#!/usr/bin/env bash
# view how much data is being/waiting to be written to disk
# see: https://github.com/torvalds/linux/blob/master/Documentation/filesystems/proc.rst#meminfo
#   or `LESS='+/meminfo' man proc`
#   or `man proc_meminfo` (in newer versions of `manpages`)

watch -n 1 'grep "Dirty\|Writeback" /proc/meminfo'
