#!/usr/bin/env bash

if [[ $OSTYPE != "darwin"* ]]; then
    echo >&2 "unsupported: darwin only"
    exit 1
fi

osascript -e 'quit app "Docker"'
while pgrep com.docker.backend >/dev/null; do
    printf '.'
    sleep 1
done && echo
