#!/bin/bash

if ! mountpoint -q /media/data; then
    echo >&2 "data not mounted"
    exit 1
fi

if [[ -L /dev/mapper/vg_deb-lv_data ]]; then
    sudo umount /media/data
else
    sudo umount /media/data && sudo cryptdisks_stop data
fi
